import { type FormEventHandler, useEffect, useState } from "react";

import Head from "next/head";
import Link from "next/link";

import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

import { Input } from "~/components/ui/input";
import { Button } from "~/components/ui/button";

import { useToast } from "~/components/ui/use-toast";

import { type Movie, getRandomMovie, movieSchema } from "~/data/movies";
import Hint from "~/components/Hint";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { toast } = useToast();

  const [movie, setMovie] = useState<Movie | undefined>(undefined);
  const [guess, setGuess] = useState("");

  const setRandomMovie = () => setMovie(getRandomMovie());

  useEffect(() => {
    setRandomMovie();
  }, []);

  const sanitizeString = (string: string) => {
    return string.trim().toLocaleLowerCase();
  };

  const handleGuess: FormEventHandler = (e) => {
    e.preventDefault();

    const parsedMovie = movieSchema.parse(movie);

    const sanitizedGuess = sanitizeString(guess);
    const sanitizedTitle = sanitizeString(parsedMovie.title);

    const isGuessCorrect = sanitizedGuess === sanitizedTitle;

    if (!isGuessCorrect) {
      toast({
        title: "Incorrect guess...",
      });

      return;
    }

    toast({
      title: "Correct guess!",
    });

    setGuess("");
    setRandomMovie();
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <section className="container my-20 text-center">
          <h1 className="text-4xl font-bold sm:text-5xl">
            Movie Emoji Guesser
          </h1>
          <p className="mt-8 text-lg">
            Can you guess the movie hidden behind these emojis ?
          </p>
        </section>

        <section className="container my-24">
          <div className="mx-auto max-w-lg">
            <section className="rounded-xl border bg-card text-card-foreground shadow">
              <h2 className="sr-only">Emoji</h2>

              <div className="px-4 py-8">
                {movie && (
                  <p className="text-center text-5xl tracking-[1rem]">
                    {movie.emoji}
                  </p>
                )}

                {movie === undefined && (
                  <p className="text-center text-5xl tracking-[1rem]">
                    Loading...
                  </p>
                )}
              </div>
            </section>

            <br />

            <form className="flex w-full max-w-lg items-center space-x-2">
              <Input
                type="guess"
                placeholder="Guess"
                onChange={(e) => setGuess(e.target.value)}
                className="py-5"
              />
              <Button type="submit" onClick={handleGuess}>
                Guess
              </Button>
            </form>

            <br />

            <section className="rounded-xl border bg-card p-8 text-card-foreground shadow">
              <h2 className="text-lg font-bold">Hints</h2>

              <hr className="my-4 mb-5" />

              {movie && (
                <div className="space-y-6">
                  <Hint hint="Year" answer={movie?.release_year} />
                  <Hint hint="Genre" answer={movie?.genres} />
                  <Hint hint="Director" answer={movie?.directors} />
                  <Hint hint="Features" answer={movie?.featured_actors} />
                </div>
              )}
            </section>

            <br />

            <Button onClick={setRandomMovie} className="w-full">
              Another movie...
            </Button>
          </div>
        </section>
      </main>
    </>
  );
}
